/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'menu_opciones.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'menu_opciones.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    model   = require('./menu_opciones.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("opcion_padre_fkeys").onDelete = 'CASCADE'; 
util.getAttribute("menu_opcion_id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.menu_opciones",
    options: {
        tableName: "menu_opciones",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "menu_opcion_id": {
            type: Seq.INTEGER,
            field: "menu_opcion_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "menu_opciones_pk"
        },
        "opcion": {
            type: Seq.STRING(50),
            field: "opcion",
            allowNull: false
        },
        "href": {
            type: Seq.STRING(250),
            field: "href"
        },
        "alias": {
            type: Seq.STRING(250),
            field: "alias"
        },
        "tooltip": {
            type: Seq.STRING(250),
            field: "tooltip"
        },
        "icono": {
            type: Seq.STRING(250),
            field: "icono"
        },
        "opcion_padre": {
            type: Seq.INTEGER,
            field: "opcion_padre",
            references: {
                model: "public.menu_opciones",
                key: "opcion_padre"
            }
        },
        "posicion": {
            type: Seq.INTEGER,
            field: "posicion"
        },
        "estado": {
            type: Seq.STRING(50),
            field: "estado"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.menu_opciones",
        schema: "public",
        table: "menu_opciones",
        source: "generator",
        details: {
            as: "opcion_padre_fkeys",
            foreignKey: "opcion_padre",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.usuario_menu_opciones",
        schema: "public",
        table: "usuario_menu_opciones",
        source: "generator",
        details: {
            as: "usuario_menu_opciones_menu_opcion_id_fkeys",
            foreignKey: "menu_opcion_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.menu_opciones",
        schema: "public",
        table: "menu_opciones",
        source: "generator",
        details: {
            as: "related_opcion_padre",
            foreignKey: "opcion_padre",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.usuarios",
        schema: "public",
        table: "usuarios",
        source: "generator",
        details: {
            as: "related_usuario_menu_opciones_menu_opcion_id_fkey_usernames",
            foreignKey: "menu_opcion_id",
            otherKey: "username",
            through: "usuario_menu_opciones",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};