/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'usuarios.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'usuarios.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./usuarios.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("usuario_menu_opciones_username_fkeys").onDelete = 'CASCADE'; 
util.getAttribute("username").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.usuarios",
    options: {
        tableName: "usuarios",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "username": {
            type: Seq.TEXT,
            field: "username",
            primaryKey: true,
            allowNull: false,
            unique: "usuarios_pkey"
        },
        "password": {
            type: Seq.STRING(50),
            field: "password",
            allowNull: false
        },
        "nombre": {
            type: Seq.STRING(50),
            field: "nombre",
            allowNull: false
        },
        "apellido": {
            type: Seq.STRING(50),
            field: "apellido",
            allowNull: false
        },
        "fecha_creacion": {
            type: Seq.DATE,
            field: "fecha_creacion"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.usuario_menu_opciones",
        schema: "public",
        table: "usuario_menu_opciones",
        source: "generator",
        details: {
            as: "usuario_menu_opciones_username_fkeys",
            foreignKey: "username",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.menu_opciones",
        schema: "public",
        table: "menu_opciones",
        source: "generator",
        details: {
            as: "usuario_menu_opciones_username_fkey_menu_opcions",
            foreignKey: "username",
            otherKey: "menu_opcion_id",
            through: "usuario_menu_opciones",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};